workspace:
  base: /srv/app
  path: src/github.com/gopad/gopad-cli

branches:
  - master

pipeline:
  cache-restore:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    restore: true
    when:
      local: false

  cli-prepare:
    image: webhippie/golang:edge
    pull: true
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make clean
      - make retool
      - make sync
      - make generate

  cli-vet:
    image: webhippie/golang:edge
    pull: true
    group: cli
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make vet

  cli-check:
    image: webhippie/golang:edge
    pull: true
    group: cli
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make megacheck

  cli-lint:
    image: webhippie/golang:edge
    pull: true
    group: cli
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make lint

  cli-test:
    image: webhippie/golang:edge
    pull: true
    group: cli
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make test

  cli-build:
    image: webhippie/golang:edge
    pull: true
    group: cli
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make build

  cli-windows:
    image: karalabe/xgo-latest:latest
    pull: true
    group: release
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make release-dirs release-windows
    when:
      event: [ push, tag ]

  cli-linux:
    image: karalabe/xgo-latest:latest
    pull: true
    group: release
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make release-dirs release-linux
    when:
      event: [ push, tag ]

  cli-darwin:
    image: karalabe/xgo-latest:latest
    pull: true
    group: release
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make release-dirs release-darwin
    when:
      event: [ push, tag ]

  cli-finish:
    image: webhippie/golang:edge
    pull: true
    environment:
      - CGO_ENABLED=0
      - GOPATH=/srv/app
      - TAGS=
    commands:
      - make release-copy release-check
    when:
      event: [ push, tag ]

  cli-gpgsign:
    image: plugins/gpgsign:1
    pull: true
    secrets: [ gpgsign_key, gpgsign_passphrase ]
    detach_sign: true
    files:
      - dist/release/*
    excludes:
      - dist/release/*.sha256
    when:
      event: [ push, tag ]

  docker-amd64:
    image: plugins/docker:17.05
    pull: true
    group: docker
    secrets: [ docker_username, docker_password ]
    repo: gopad/gopad-cli
    auto_tag: true
    auto_tag_suffix: amd64
    when:
      event: [ push, tag ]

  docker-i386:
    image: plugins/docker:17.05
    pull: true
    group: docker
    secrets: [ docker_username, docker_password ]
    repo: gopad/gopad-cli
    dockerfile: Dockerfile.i386
    auto_tag: true
    auto_tag_suffix: i386
    when:
      event: [ push, tag ]

  docker-arm64:
    image: plugins/docker:17.05
    pull: true
    group: docker
    secrets: [ docker_username, docker_password ]
    repo: gopad/gopad-cli
    dockerfile: Dockerfile.arm64
    auto_tag: true
    auto_tag_suffix: arm64
    when:
      event: [ push, tag ]

  docker-arm:
    image: plugins/docker:17.05
    pull: true
    group: docker
    secrets: [ docker_username, docker_password ]
    repo: gopad/gopad-cli
    dockerfile: Dockerfile.arm
    auto_tag: true
    auto_tag_suffix: arm
    when:
      event: [ push, tag ]

  docker-manifests:
    image: plugins/manifest:1
    pull: true
    secrets: [ docker_username, docker_password ]
    spec: manifest.yml
    auto_tag: true
    ignore_missing: true
    when:
      event: [ push, tag ]

  docker-microbadger:
    image: plugins/webhook:1
    pull: true
    secrets:
      - source: microbadger_token
        target: plugin_urls
    when:
      event: [ push, tag ]

  cache-rebuild:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    rebuild: true
    mount:
      - _tools
      - vendor
    when:
      local: false
      event: [ push ]

  cache-flush:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    flush: true
    flush_age: 14
    when:
      local: false
      event: [ push ]

  archive-release:
    image: plugins/s3:1
    pull: true
    secrets: [ s3_endpoint, aws_access_key_id, aws_secret_access_key, s3_bucket ]
    source: dist/release/*
    target: /cli/master
    strip_prefix: dist/release/
    path_style: true
    when:
      event: [ push ]

  archive-release:
    image: plugins/s3:1
    pull: true
    secrets: [ s3_endpoint, aws_access_key_id, aws_secret_access_key, s3_bucket ]
    source: dist/release/*
    target: /cli/${DRONE_TAG##v}
    strip_prefix: dist/release/
    path_style: true
    when:
      event: [ tag ]

  github-release:
    image: plugins/github-release:1
    pull: true
    secrets: [ github_token ]
    files:
      - dist/release/*
    when:
      event: [ tag ]

  notify-matrix:
    image: plugins/matrix:1
    pull: true
    secrets: [ matrix_roomid, matrix_username, matrix_password ]
    when:
      local: false
      events: [ push, tag ]
      status: [ changed, failure ]
