# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - id: cli
    main: ./cmd/gopad-cli
    binary: gopad-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -extldflags "-static" -X "github.com/gopad/gopad-cli/pkg/version.String={{.Version}}" -X "github.com/gopad/gopad-cli/pkg/version.Revision={{.Commit}}" -X "github.com/gopad/gopad-cli/pkg/version.Date={{.Date}}"
    tags:
      - netgo
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - "386"
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm

archives:
  - id: cli
    ids:
      - cli
    name_template: "gopad-cli-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - CHANGELOG.md
      - src: cmd/gopad-cli/README.md
        dst: README.md

nfpms:
  - id: cli
    ids:
      - cli
    package_name: gopad-cli
    file_name_template: "gopad-cli-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}"
    vendor: Gopad
    homepage: https://gopad.eu
    maintainer: Thomas Boerger <thomas@webhippie.de>
    description: |-
      CLI for etherpad for markdown with Go
    license: Apache 2.0
    formats:
      - deb
      - rpm

signs:
  - id: archives
    signature: "${artifact}.asc"
    cmd: gpg2
    artifacts: archive
    args:
      - --batch
      - --armor
      - --local-user
      - 64430B277E1E4090BF4C00E307A9B72C9FE6469C
      - --output
      - ${signature}
      - --detach-sign
      - ${artifact}
  - id: packages
    signature: "${artifact}.asc"
    cmd: gpg2
    artifacts: package
    args:
      - --batch
      - --armor
      - --local-user
      - 64430B277E1E4090BF4C00E307A9B72C9FE6469C
      - --output
      - ${signature}
      - --detach-sign
      - ${artifact}

snapshot:
  version_template: testing

changelog:
  disable: true

checksum:
  disable: false
  split: true
