# escape=`
FROM microsoft/nanoserver:10.0.14393.2430

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" `
  org.label-schema.name="Gopad CLI" `
  org.label-schema.vendor="Thomas Boerger" `
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["c:\\gopad-cli.exe"]
CMD ["help"]

COPY bin/gopad-cli.exe c:\gopad-cli.exe
