FROM arm32v6/alpine:3.20

RUN apk add --no-cache ca-certificates mailcap && \
    addgroup -g 1337 gopad && \
    adduser -D -u 1337 -h /var/lib/gopad -G gopad gopad

ENTRYPOINT ["/usr/bin/gopad-cli"]
CMD ["help"]

COPY bin/gopad-cli /usr/bin/gopad-cli
WORKDIR /var/lib/gopad
USER gopad
